/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_nisble_droidsweeper_MineSweeperMatrix */

#ifndef _Included_de_nisble_droidsweeper_MineSweeperMatrix
#define _Included_de_nisble_droidsweeper_MineSweeperMatrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_nisble_droidsweeper_MineSweeperMatrix
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_nisble_droidsweeper_MineSweeperMatrix_init
  (JNIEnv *, jobject);

/*
 * Class:     de_nisble_droidsweeper_MineSweeperMatrix
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_nisble_droidsweeper_MineSweeperMatrix_free
  (JNIEnv *, jobject);

/*
 * Class:     de_nisble_droidsweeper_MineSweeperMatrix
 * Method:    nativeNewMatrix
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_nisble_droidsweeper_MineSweeperMatrix_nativeNewMatrix
  (JNIEnv *, jobject);

/*
 * Class:     de_nisble_droidsweeper_MineSweeperMatrix
 * Method:    nativeRegisterCallback
 * Signature: (Ljava/lang/Object;Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_de_nisble_droidsweeper_MineSweeperMatrix_nativeRegisterCallback
  (JNIEnv *, jobject, jobject, jstring, jint, jint);

/*
 * Class:     de_nisble_droidsweeper_MineSweeperMatrix
 * Method:    nativeRevealField
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_de_nisble_droidsweeper_MineSweeperMatrix_nativeRevealField
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class de_nisble_droidsweeper_MineSweeperMatrix_FieldStatus */

#ifndef _Included_de_nisble_droidsweeper_MineSweeperMatrix_FieldStatus
#define _Included_de_nisble_droidsweeper_MineSweeperMatrix_FieldStatus
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
